#!/bin/sh
exec 2>&1
for i in $(seq 1 100); do [ -S /run/dbus/system_bus_socket ] && break; sleep 0.1; done
[ -S /run/dbus/system_bus_socket ] || exit 1
exec /usr/lib/bluetooth/bluetoothd -n -P battery
